# Site settings
title: web JoJo
email: stefan.mitev@webjojo.net
description: My personal blog
baseurl: "/site"
url: "http://goroner.github.io"

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

paginate: 5

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

exclude: [bower_components]